### PR TITLE
Url.percentEncode also path segments

### LINKED ISSUE #25: path should also be escaped
```elm
Url.Builder.absolute ["file", "/path/bla"] []
```
should result to 

```
/file/%2Fpath%2Fbla
```

but currently results to

```
/file//path/bla
```

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes #25

### CODE REVIEW

**Comment by hpate-omicron** [comment]
This would be great to have, it is a confusing issue to run into

**Comment by domenkozar** [comment]
@evancz I'd appreciate if this was merged.

**Comment by hpate-omicron** [comment]
This would be nice to get in line with the RFC, this is the spec section for this piece that mentions percent encoding the path segments.
https://tools.ietf.org/html/rfc3986#section-3.3

**Comment by joshuakb2** [comment]
Is this fix going to be merged, and if not, why not?

**Comment by joshuakb2** [comment]
Is there any reason this hasn't been merged for over a year? I keep getting emails when people update the issue because they felt misled by the documentation. @domenkozar already fixed it, it just has to be merged. Is there something lacking here?

@evancz, can you help here? I don't know who else has the power to help us move forward on this issue.

**Pull request closed without merging**
